language: go
dist: xenial
cache:
  - apt: true

go:
  - "1.13.x"

services:
  - docker

branches:
  only:
    - master
    - dev
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

jobs:
  include:
    - stage: "build and run test"

      os: linux
      before_install:
        - go version
      install:
        - go mod tidy
        - |
          os=$(go env GOOS)
          arch=$(go env GOARCH)
          curl -sL https://go.kubebuilder.io/dl/2.1.0/${os}/${arch} | tar -xz -C /tmp/
          sudo mv /tmp/kubebuilder_2.1.0_${os}_${arch} /usr/local/kubebuilder
        - |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.21.0
          export PATH="$PATH:$(pwd)/bin"
      before_script:
        - go mod tidy
      script:
        - make lint
        - make coverage
        - mv $GOPATH/out/codecov/coverage.cov ./coverage.out
        - cat coverage.out
        - go test -json ./... > tests.json
        - cat tests.json