 required = [  
  "k8s.io/code-generator/cmd/deepcopy-gen"]

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/klog"
  version = "v2.0.0"  

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"  

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/cluster-registry"
  version = "0.0.6"

[[override]]
  name = "github.com/stretchr/testify" 

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[prune]
  go-tests = true
