apiVersion: policies.ibm.com/v1alpha1
kind: ConfigurationPolicy
metadata:
  name: example-configurationpolicy-3
spec:
  severity: low
  namespaceSelector:
    include: ["default","kube-*"]
    exclude: ["kube-system"]
  remediationAction: inform
  maxClusterRoleBindingGroups: 10
  maxClusterRoleBindingUsers: 10
  maxRoleBindingGroupsPerNamespace: 2
  maxRoleBindingUsersPerNamespace: 2
